[package]
name = "waves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.14.0" }
bevy_simple_text_input = "0.8.0"
uom = "0.36.0"
once_cell = "1.19.0"
